name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.16', '1.15', '1.14' ]
    name: golangci-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          level: error
          fail_on_error: true
      - name: Coverage Tests
        run: go test . -cover -race -coverprofile=profile.cov
      - name: Send coverage
        if: ${{ matrix.go == '1.16' }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
